In [1]:
import numpy as np

In [3]:
#creating sample array
arr=np.arange(0,11)


In [4]:
#show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [18]:

arr[0:5]=100
arr


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
arr1=list(range(0,11))
arr1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [16]:
arr1[0:5]=[100]*5

In [17]:
type(arr1)

list

In [19]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
slice_of_arr=arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [21]:
slice_of_arr[:]=99

In [22]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [25]:
#to get a copy,need to be explicit
arr_copy=arr.copy()

In [26]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr_2d=np.array(([5,10,15],[20,25,30],[35,40,45]))
#show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
#indexing row
arr_2d[1]

array([20, 25, 30])

In [29]:
#format is arr_2d[row][col]or arr_2d[row,col]
#getting individual element value
arr_2d[1][0]

20

In [30]:
arr_2d[1,0]

20

In [31]:
#2D array slicing
#Shape (2,2)from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [32]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [33]:
arr_2d[2,:]

array([35, 40, 45])

In [37]:
arr_2d=np.array(([1,2,3],[4,5,6],[7,8,9]))
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr_2d[2:,:].shape

(1, 3)

In [39]:
arr_2d[2].shape

(3,)

In [11]:
arr_2d[2,:].shape

NameError: name 'arr_2d' is not defined

In [8]:
arr_2d[:]

NameError: name 'arr_2d' is not defined

In [44]:
#set up matrix
arr2d=np.zeros((10,10))

In [45]:
arr_length=arr2d.shape[1]

In [46]:
#Set up array
for i in range(arr_length):
    arr2d[i]=i

In [47]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [52]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [54]:
arr2d[:,[2,4,6,8]]

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.],
       [8., 8., 8., 8.],
       [9., 9., 9., 9.]])

In [55]:
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [58]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [60]:
bool_arr=arr>4

In [61]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [62]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [63]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
x=2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])